# Generated by Django 3.2 on 2023-01-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_code_session_and_order'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('number_of_payments', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customercards')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
