# Generated by Django 4.1.5 on 2023-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
