# Generated by Django 4.1.5 on 2023-09-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
