# Generated by Django 3.2 on 2022-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_plan', to='products.planproducts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.profile')),
            ],
        ),
    ]
