# Generated by Django 3.2 on 2022-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_code',
            field=models.CharField(default='F032B680', max_length=50),
        ),
    ]
