# Generated by Django 3.2 on 2022-12-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_orders_order_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(default='48772F17', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_token', models.CharField(blank=True, max_length=50, null=True)),
                ('card_masked_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.profile')),
            ],
        ),
    ]
