# Generated by Django 3.2 on 2022-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_create_customer_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercards',
            options={'verbose_name': 'Customer Card', 'verbose_name_plural': 'Customer Cards'},
        ),
        migrations.AddField(
            model_name='customercards',
            name='card_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(default='ACB75A89', max_length=50),
        ),
    ]
