# Generated by Django 4.1.5 on 2023-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_field_card_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_api_user',
            field=models.BooleanField(default=False),
        ),
    ]
