# Generated by Django 3.2 on 2022-12-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercards',
            name='alias_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customercards',
            name='card_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customercards',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(default='CD584F00', max_length=50),
        ),
    ]
