# Generated by Django 3.2 on 2022-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_creation_date_autonow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.CharField(max_length=50),
        ),
    ]
