# Generated by Django 4.1.5 on 2023-09-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_plan_fee_amount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
