# Generated by Django 3.2 on 2022-12-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_plan_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='planproducts',
            options={'verbose_name': 'Product Plan', 'verbose_name_plural': 'Product Plans'},
        ),
    ]
